variables:
  - &node_image 'node:16-alpine'
  - &when_path
      # web source code
      - "web/**"
  - &when
    - event: tag
    - event: pull_request
      path: *when_path
    - event: push
      branch: ${CI_REPO_DEFAULT_BRANCH}
      path: *when_path

pipeline:
  deps:
    image: *node_image
    commands:
      - cd web/
      - yarn install --frozen-lockfile
    when: *when

  lint:
    group: test
    image: *node_image
    commands:
      - cd web/
      - yarn lint
    when: *when

  formatcheck:
    group: test
    image: *node_image
    commands:
      - cd web/
      - yarn formatcheck
    when: *when

  typecheck:
    group: test
    image: *node_image
    commands:
      - cd web/
      - yarn typecheck
    when: *when

  test:
    group: test
    image: *node_image
    commands:
      - cd web/
      - yarn test
    when: *when
